# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt /app/

# Install any needed packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container
COPY . /app/

# Expose port 8000 for the Django app
EXPOSE 8000

# Define environment variable
ENV DJANGO_SETTINGS_MODULE=cofolio_project.settings

# Run the application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
